CREATE DATABASE ECommerceGem

CREATE TABLE Category
(
	CategoryId INT PRIMARY KEY IDENTITY(1,1),
	CategoryName VARCHAR(100) NOT NULL,
	CategoryImageUrl VARCHAR(MAX) NOT NULL,
	IsActive BIT NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE SubCategory
(
	SubCategoryId INT PRIMARY KEY IDENTITY(1,1),
	SubCategoryName VARCHAR(100) NOT NULL,
	CategoryId INT FOREIGN KEY REFERENCES Category(CategoryId) ON DELETE CASCADE NOT NULL,
	IsActive BIT NOT NUll,
	CreatedDate DATETIME NOT NULL
 )

 CREATE TABLE Product
(
	ProductId INT PRIMARY KEY IDENTITY(1,1),
	ProductName VARCHAR(100) NOT NULL,
	ShortDescription VARCHAR(200) NULL,
	LongDescription VARCHAR(MAX) NULL,
	AdditionalDescription VARCHAR(MAX) NULL,
	Price DECIMAL(18,2) NOT NULL,
	Quantity INT NOT NULL,
	Size VARCHAR(30) NULL,
	Color VARCHAR(50) NULL,
	CompanyName VARCHAR(100) NULL,
	CategoryId INT FOREIGN KEY REFERENCES Category(CategoryId) ON DELETE CASCADE NOT NULL,
	SubCategoryId INT NOT NULL,
	Sold INT NULL,
	IsCustomized BIT NOT NULL,
	IsActive BIT NOT NUll,
	CreatedDate DATETIME NOT NULL
)
CREATE TABLE ProductImages
(
	ImageId INT PRIMARY KEY IDENTITY(1,1),
	ImageUrl VARCHAR(MAX) NULL,
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	DefaultImage BIT NULL
)

CREATE TABLE Roles
(
	RoleId INT PRIMARY KEY,
	RoleName VARCHAR(50) NOT NULL
)

INSERT INTO Roles VALUES(1,'Admin')
INSERT INTO Roles VALUES(2,'Customer')

CREATE TABLE Users
(
	UserId INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NULL,
	Username VARCHAR(50) NULL UNIQUE,
	Mobile VARCHAR(20) NULL,
	Email VARCHAR(50) NULL,
	Address VARCHAR(MAX) NULL,
	PostCode VARCHAR(50) NULL,
	Password VARCHAR(50) NULL,
	ImageUrl VARCHAR(MAX) NULL,
	RoleId INT FOREIGN KEY REFERENCES Roles(RoleId) ON DELETE CASCADE NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE ProductReview
(
	ReviewId INT PRIMARY KEY IDENTITY(1,1),
	Rating INT NOT NULL,
	Comment VARCHAR(MAX),
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users(UserId) ON DELETE CASCADE NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE Wishlist
(
	WishlistId INT PRIMARY KEY IDENTITY(1,1),
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users(UserId) ON DELETE CASCADE NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE Cart
(
	CartId INT PRIMARY KEY IDENTITY(1,1),
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	Quantity INT NULL,
	UserId INT FOREIGN KEY REFERENCES Users(UserId) ON DELETE CASCADE NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE Contact
(
	ContactId INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NULL,
	Email VARCHAR(50) NULL,
	Subject VARCHAR(200) NULL,
	Message VARCHAR(MAX) NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE Payment
(
	PaymentId INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NULL,
	CardNumber VARCHAR(50) NULL,
	ExpirationDate VARCHAR(50) NULL,
	CvvNumber INT NULL,
	Address VARCHAR(MAX) NULL,
	PaymentMode VARCHAR(50) NULL,
)

CREATE TABLE Orders
(
	OrderDatailsId INT PRIMARY KEY IDENTITY(1,1),
	OrderNumber VARCHAR(MAX) NULL,
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	Quantity INT NULL,
	UserId INT FOREIGN KEY REFERENCES Users(UserId) ON DELETE CASCADE NOT NULL,
	Status VARCHAR(50) NULL,
	PaymentId INT FOREIGN KEY REFERENCES Payment(PaymentId) ON DELETE CASCADE NOT NULL,
	OrderDate DATETIME NOT NULL,
	IsCancel BIT NOT NULL DEFAULT 0
)

